# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: lhumbert <marvin@42lausanne.ch>            +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2021/10/14 17:48:26 by lhumbert          #+#    #+#              #
#    Updated: 2022/10/26 21:34:03 by loichu           ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

FILE_PATH   :=  $(abspath $(lastword $(MAKEFILE_LIST)))

include	module.config.mk
include	../modules.config.mk