# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: vnicoud <vnicoud@student.42.fr>            +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2022/10/21 13:05:06 by vnicoud           #+#    #+#              #
#    Updated: 2022/11/08 17:33:29 by loichu           ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

FILE_PATH   :=  $(abspath $(lastword $(MAKEFILE_LIST)))

include	module.config.mk
include	../modules.config.mk
